version: '3.3'
services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgers
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./.docker/db:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
      
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    container_name: minio
    command: server ${MN_PATH} --console-address ":${MN_CONSOLE_PORT}"
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MN_ACCESSKEY_ID}
      - MINIO_ROOT_PASSWORD=${MN_SECRET_ACCESSKEY}
    ports:
      - "${MN_EXTERNAL_PORT}:9000"
      - "${MN_EXTERNAL_CONSOLE_PORT}:${MN_CONSOLE_PORT}"
    volumes:
     - ./.docker/storage:${MN_PATH}
  
  service:
    image: dyleme/apod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: apod
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgresql
      - minio