version: '3.3'
services:
  postgresql:
    image: postgres
    restart: always
    container_name: postgers
    env_file: .env
    environment:
      - POSTGRES_USER=${DBUSERNAME}
      - POSTGRES_PASSWORD=${DBPASSWORD}
      - POSTGRES_DB=${DBNAME}
    ports:
      - 5432:5432
    volumes:
      - ./.docker/db:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080
      
  minio:
    image: quay.io/minio/minio:latest
    restart: always
    container_name: minio
    command: server ${MNPATH} --console-address ":9001"
    env_file: .env
    environment:
      - MINIO_ROOT_USER=${MNACCESSKEYID}
      - MINIO_ROOT_PASSWORD=${MNSECRETACCESSKEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
     - ./.docker/storage:/storage/
  
  service:
    image: dyleme/apod
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: apod
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - minio